# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gc8XEj6A4f4QRyZc43HkuXoJqTjtFtsW
"""



# 1. yol

points = [(3,7), (5,9)]

def euclideanDistance(points):
  """
  This function calculates the euclidean distance.
  """
  distances = []
  for i in range(len(points)-1):
    x1, y1 = points[i]
    x2, y2 = points[i + 1]
    d = ((x2 - x1) ** 2 + (y2 - y1) ** 2) ** 0.5
    distances.append(d)
  return f'Distances: {distances}'

euclideanDistance(points)

# 2. yol

import math

points = [(3,7), (5,9)]

def euclideanDistance(points):
  """
  This function calculates the euclidean distance.
  """
  distances = []
  for i in range(len(points)-1):
    x1, y1 = points[i]
    x2, y2 = points[i + 1]
    d = math.sqrt((x2 - x1)**2 + (y2 - y1)**2)
    distances.append(d)
  return f'Distances: {distances}'

euclideanDistance(points)

